name: "polls_only_debug"
model_name: "PollOnlyModel"
year: 2016
pymc:
  n_samples: 5
  n_chains: 2
  n_cores: 4
  n_tune_steps: 5
  target_accept: 0.99
  max_treedepth: 13
model_kwargs:
  forecast_horizon: 7
  prior_precision: 10
  state_variance_prior_bias: 1.0e-4
  state_variance_prior_sigma: 1.0
  national_variance_prior_bias: 1.0e-4
  national_variance_prior_sigma: 0.5
  national_final_variance: 1.0e-6